language: go

go:
    - 1.4.x
    - 1.7.x
    - master

services:
    - mysql

before_install:
    - mysql -e 'CREATE DATABASE go_on_rails_test;'

install:
    - go get github.com/jmoiron/sqlx
    - go get github.com/go-sql-driver/mysql
    - go get github.com/asaskevich/govalidator
    - rvm install 2.3.4 --default
    - bundle install --jobs=3 --retry=3
    - rails db:migrate
    - rails db:seed
    - rails generate gor test

script: go test ./go_app/models
