# This test focuses on the generated Go codes to make things simple:
# 1. Ruby use v2.3.4, specified in the Gemfile due to it's available in Travis-ci by default
# 2. Rails is v5.0.2, also specified in Gemfile, it'll be installed by bundler
# 3. we just test MySQL database using the Travis-ci's default service version
# 4. and we set RAILS_ENV=test in Travis-ci's Environment Variables setting

language: go

go:
    - 1.7.x
    - 1.8.x
    - 1.9.x
    - master

services:
    - mysql

before_install:
    - mysql -e 'CREATE DATABASE go_on_rails_test;'

install:
    - go get github.com/jmoiron/sqlx
    - go get github.com/go-sql-driver/mysql
    - go get github.com/asaskevich/govalidator
    - rvm install 2.3.4 --default
    - bundle install --jobs=3 --retry=3
    - rails db:migrate
    - rails db:seed
    - rails generate gor test

script: go test ./go_app/models
