language: go

go:
    - 1.4.2
    - 1.5.x
    - 1.6.x
    - 1.7.x
    - 1.8.x
    - master

services:
    - mysql

before_install:
    - mysql -e 'CREATE DATABASE go-on-rails_test;'

install:
    - bundle install --jobs=3 --retry=3
    - rails generate gor test
    - rails gor:deps

script: go test ./go_app/models
