default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: go-on-rails_development

test:
  <<: *default
  host: 127.0.0.1
  database: go_on_rails_test

production:
  <<: *default
  database: go-on-rails_production
  username: go-on-rails
  password: <%= ENV['GO-ON-RAILS_DATABASE_PASSWORD'] %>

test_sqlite:
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: db/test.sqlite3

test_postgres:
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: go-on-rails_test_postgres
  username: test_postgres
  password: secret
